//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pajocoons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aanvraag
    {
        public int aanvraagID { get; set; }
        public string aanvraagDatum { get; set; }
        public string beschrijving { get; set; }
        public string kleur { get; set; }
        public string type { get; set; }
        public string karakter { get; set; }
        public string geslacht { get; set; }
        public int persoonID { get; set; }
    
        public virtual Persoon Persoon { get; set; }
    }
}
