//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pajocoons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int adresID { get; set; }
        public string straatnaam { get; set; }
        public string huisnummer { get; set; }
        public string postcode { get; set; }
        public string gemeente { get; set; }
        public string land { get; set; }
        public string postbus { get; set; }
        public string provincie { get; set; }
        public string stad { get; set; }
    }
}
