//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pajocoons.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PajoDBObjecten : DbContext
    {
        public PajoDBObjecten()
            : base("name=PajoDBObjecten")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aanvraag> Aanvraag { get; set; }
        public DbSet<Account> Account { get; set; }
        public DbSet<Adres> Adres { get; set; }
        public DbSet<Bericht> Bericht { get; set; }
        public DbSet<Persoon> Persoon { get; set; }
        public DbSet<Setting> Setting { get; set; }
    }
}
