//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pajocoons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        public Persoon()
        {
            this.Aanvraag = new HashSet<Aanvraag>();
            this.Bericht = new HashSet<Bericht>();
        }
    
        public int persoonID { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string geboortedatum { get; set; }
        public string email { get; set; }
        public int accountID { get; set; }
        public int adresID { get; set; }
        public int settingID { get; set; }
    
        public virtual ICollection<Aanvraag> Aanvraag { get; set; }
        public virtual Account Account { get; set; }
        public virtual Adres Adres { get; set; }
        public virtual ICollection<Bericht> Bericht { get; set; }
        public virtual Setting Setting { get; set; }
    }
}
